# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCDCHAq8IaDWf92wYIIeTU_McfP9fnAW
"""

#Task 1

# Write two lines of code below, each assigning a value to a variable
# Now write a print statement using .format() to print out a sentence and the
# values of both of the variables
message= "Ghansham is {} and {}";
print(message.format("brave", "strong"))

#Task 2

str = "Ghansham"
print(str.capitalize())
print(str.casefold())
print(str.count("s", 0, len(str)))

#Task 3

month = 8
days_in_month = [31,28,31,30,31,30,31,31,30,31,30,31]
# use list indexing to determine the number of days in month
num_days = days_in_month[month - 1]
print("month", month ,"contains", num_days , "days")

#Task 4

eclipse_dates = ['June 21, 2001', 'December 4, 2002', 'November 23, 2003', 'March 29, 2006', 'August 1, 2008', 'July 22, 2009', 'July 11, 2010', 'November 13, 2012', 'March 20, 2015', 'March 9, 2016']

# TODO: Modify this line so it prints the last three elements of the list
recent_dates = eclipse_dates[-3:]

print(recent_dates)

#Task 5

students = {
    "Ghansham": {
        "age": 21,
        "semester": "6th",
        "subjects": ["DS&A", "DS", "MAD"],
        "address": {
            "street": "1 Main St",
            "city": "Mithi",
            "state": "Sindh",
            "zip": "69230"
        }
    },
    "Aashir": {
        "age": 21,
        "semester": "5th",
        "subjects": ["DWH", "IS", "CPS"],
        "address": {
            "street": "4 B St",
            "city": "Nangarparkar",
            "state": "Thar",
            "zip": "852963"
        }
    },
    # Add more students as needed
}
students["Ghansham"]["semester"],
print("ghansham")
print(students)